CREATE TABLE IF NOT EXISTS nexa_signup_attempt (
    id CHAR(36) NOT NULL,
    public_token_hash CHAR(64) NOT NULL,
    method VARCHAR(16) NOT NULL,
    provider VARCHAR(32) NULL,
    provider_subject VARCHAR(191) NULL,
    email VARCHAR(190) NOT NULL,
    normalized_email VARCHAR(190) NOT NULL,
    first_name VARCHAR(100) NULL,
    last_name VARCHAR(100) NULL,
    password_hash VARCHAR(255) NULL,
    profile_json JSON NULL,
    selected_plan_key VARCHAR(64) NULL,
    company_name VARCHAR(120) NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
    terms_accepted_at DATETIME(6) NULL,
    email_verified_at DATETIME(6) NULL,
    verification_code_hash CHAR(64) NULL,
    verification_expires_at DATETIME(6) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'profile_pending',
    expires_at DATETIME(6) NOT NULL,
    completed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_nexa_signup_attempt_token (public_token_hash),
    UNIQUE KEY uq_nexa_signup_attempt_email (normalized_email),
    KEY idx_nexa_signup_attempt_status_expiry (status, expires_at),
    KEY idx_nexa_signup_attempt_provider (provider, provider_subject)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
